name: Deploy Portfolio to EC2

on:
  push:
    branches:  
      - main  # Or your default branch
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Copy files to EC2 via SCP
      uses: appleboy/scp-action@v0.1.7 
      with:
        host: ${{ secrets.EC2_HOST }} 
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }} 
        port: 22 
        source: "index.html,css/*,img/*" 
        target: "/var/www/html" 
        strip_components: 0 